spring.application.name=StubService
stub.response.delay.min=1000
stub.response.delay.max=2000

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

db.params.host = 192.168.0.13:5432
db.params.dbname = mydatabase
db.params.username = myuser
db.params.password = mypassword